### ISSUE TITLE
SD card powering

### ISSUE THREAD

**Issue by roman-dvorak** [ust-modules/USTSIPIN02#19]
Same as https://github.com/UniversalScientificTechnologies/SPACEDOS02/issues/8#issue-1088564901

**Comment by kaklik** [comment]
Tohle souvisí s volbou vhodného spínače. Aktuálně ve skladu máme [tyhle typy](https://github.com/mlab-modules/PROGLOG01/issues/4).

**Comment by kaklik** [comment]
Navrhoval bych použít [TPS22919DCK](https://www.ti.com/product/TPS22919), který je technologicky bližší na plošném spoji aktuálně použitým součástkám.

**Comment by kaklik** [comment]
Zavedeno do schéma. Napájení SDkarty se teď bude ovládat jen PB1

![image](https://github.com/ust-modules/USTSIPIN02/assets/1194177/c34b42da-c7ba-4bee-ac35-422e2fd9eda2)
