### ISSUE TITLE
Divide analogue and digital ground 

### ISSUE THREAD

**Issue by roman-dvorak** [ust-modules/USTSIPIN02#21]

**Comment by kaklik** [comment]
Jak se to dělá je napsáno třeba tady: http://edge.rit.edu/edge/P14251/public/Schematics/Electrical/PCB%20Info/sloa089.pdf

**Comment by kaklik** [comment]
Ještě je potřeba oddělit analogovou zem u MCU. Na PCB je potřeba se podívat které GND odpovídá tahle nožička v diagramu v datasheetu. 

![image](https://github.com/ust-modules/USTSIPIN02/assets/1194177/e5ea411b-eeb3-46d7-9403-97546cb0ed12)

**Comment by kaklik** [comment]
Tak je to nožička č. 28.
