### ISSUE TITLE
SDcard holder malfunction

### ISSUE THREAD

**Issue by kaklik** [ust-modules/USTSIPIN02#24]
Při výrobě zřejmě dochází k nějakému poškození pouzdra SDkarty. Projevuje se to tak, že SDkarta do pouzdra buď nejde vůbec zastrčit. Nebo případně mechanismus na její vysouvání nefunguje dobře případně vůbec. 

Možnosti poškození, které mne napadají jsou tyhle: 

- Tepelné poškození pouzdra při pájení
- Chemické poškození čističem při omývání zbytků tavidla
- Zalepení rozpuštěným tavidlem při omývání desky

**Comment by ChroustJan** [comment]
Příliš mnoho pasty. Tavidlo pak zatýká do pouzdra a drhne.
