### ISSUE TITLE
Integrated USB

### ISSUE THREAD

**Issue by roman-dvorak** [ust-modules/USTSIPIN02#3]
Použitý MCU obsahuje dvě hardwarové UART rozhraní. Jedno rozhraní by se mohlo vyhradit pro USB, které by se používalo pro "přenosné" a "krátkodobé" aplikace, kdy by se zařízení připojovalo k uživatelskému počitači. USB by zároveň sloužilo pro nahrávání firmware pomocí [Obslužné aplikace](https://github.com/UniversalScientificTechnologies/SPACEDOS03/issues/4). 

Druhá sériovka by byla užívána pro aplikace, kde by zařízení bylo umístěné někam, kde by byl cizí UART datalogger. Nebo pro aplikace, kde je potřeba data přenášet na větší vzdálenost. Zároveň by to umožňovalo moct změnit firmware/konfiguraci zařízení po USB bez rozpojování zařizení či demontáže. 

Díky integraci USB by SPACEDOS03A se stal velmi kompaktním a odolným zařízením. Následně by se pro zařízení mohla vyvinout nějaká tištěná/frézovaná hliníková krabička. 

Nepříjemností pro vyřešení tohoto kroku je, že nemáme vyrobený a otestovaný [RS232R02](https://github.com/mlab-modules/USB232R02) převodní, který by se do USTSIPINu mohl zaintegrovat. Zároveň by měl (z pohledu životnosti/odolnosti) nejhorší pouzdro z celého modulu. Převodník však existuje ve variantě [SSOP](https://ftdichip.com/wp-content/uploads/2021/10/DS_FT231X.pdf).
Potřebné kroky:
- [ ] Ověřit, že vybraný převodník je vhodný
- [ ] Upravit návrh PCB
- [ ] Navrhnout vnější design produktu (krabička, potisk, ..)

**Comment by kaklik** [comment]
Tohle issue by podle mého mělo být součástí https://github.com/UniversalScientificTechnologies/SPACEDOS03 nikoliv tohoto detektčního modulu.

**Comment by roman-dvorak** [comment]
Nesouhlasím.

**Comment by roman-dvorak** [comment]
Nesouhlasím, protože tohle issue řeši integraci přímo do PCB za účelem kompaktnosti a zvětšení user-experience. A ne jako další MLAB modul.

**Comment by kaklik** [comment]
> Nesouhlasím, protože tohle issue řeši integraci přímo do PCB za účelem kompaktnosti a zvětšení user-experience. A ne jako další MLAB modul.

Ano, to jsem pochopil. Ale řeší to jako vlastnost toho výslednýho zařízení, Nikoliv jako vlastost detekční části (což bylo původně smyslem tohoto modulu a repozitáře). Pokud to tak už není, tak se to PCB má přímo jmenovat SPACEDOS03 a být přímo v repozitáři SPACEDOS03. Nedává pak smysl mít oddělený moduly, když v tom zařízení pak nic jiného nebude.

**Comment by roman-dvorak** [comment]
Má to smysl. Protože SPACEDOS03 může mít další specifika oproti USTSIPIN01. Ať už nějaký způsob montáže (tj. krabička) nebo to může být následně využito v nějakých dalších kompletních celcích, kam se to dá přidat jako submodul. S tím, že to bude mít vlastnost, že to například lze například programovat přes USB.

Já to moc nechápu už třeba jen z důvodu, že jsi mi tvrdil, že použitý procesor má jednu hardwarovou sériovku. A přišel jsem s tím, že by to mohlo mít jako rozhraní i USB. Takže to oproti té tvé původnů představě (s jedním vyvedeným UARTEM) to zůstává stále kompatibilní.

**Comment by kaklik** [comment]
> Má to smysl. Protože SPACEDOS03 může mít další specifika oproti USTSIPIN01. Ať už nějaký způsob montáže (tj. krabička) nebo to může být následně využito v nějakých dalších kompletních celcích, kam se to dá přidat jako submodul. S tím, že to bude mít vlastnost, že to například lze například programovat přes USB.
>

Ano, to zase chápu, ale zároveň přidání USB na stejný modul, kde budou kromě USB vyvedeny i obě seriové linky zavádí značnou komplikaci v návrhu toho modulu. Tudíž mi přijde rozumné to udržet co nejjednodušší a: 

1. Udělat separátní zařízení které na jedné seriovce bude umožňovat připojení jen přes USB. (Což je asi ten SPACEDOS03 ve formě nového specifického PCB, což mi původně připadalo jako enormně náročný řešení, dokud nepřišel @ChroustJan  s ještě mnohem složitějším návrhem)
2. Nebo mít zařízení (modul), které má vyvedenou jen čistou seriovku na kterou lze něco připojit bez nějakých dalších "překvapení".
 
> Já to moc nechápu už třeba jen z důvodu, že jsi mi tvrdil, že použitý procesor má jednu hardwarovou sériovku. A přišel jsem s tím, že by to mohlo mít jako rozhraní i USB. Takže to oproti té tvé původnů představě (s jedním vyvedeným UARTEM) to zůstává stále kompatibilní.

Myslel jsem si, že ta druhá seriovka se tam dělá softwarově. Nikoliv že na tom modulu bude pouze jen jedna seriová linka. Dvě tam jsou potřeba z toho důvodu, že je k tomu občas potřeba připojit GPS a zároveň mít připojený nějaký nadřazený logger. Netušil jsem že teď je to vyřešené tak, že i ta druhá UART linka je taky HW (a když to tak je, tak bych to nerad měnil).

**Comment by roman-dvorak** [comment]
> Nebo mít zařízení (modul), které má vyvedenou jen čistou seriovku na kterou lze něco připojit bez nějakých dalších "překvapení".

Tak z toho důvodu k tomu také poskytujeme schémata. Aby to nebylo "překvapením" ale aby s tím člověk počital. A prostě to bral jako vlastnost tohoto zařizení, že tam bude 200k pullup. 

Navíc druhá sériovka to bude stále splňovat. 

> Netušil jsem že teď je to vyřešené tak, že i ta druhá UART linka je taky HW (a když to tak je, tak bych to nerad měnil).

Tak rušit jí rozhodně nechceme.

**Comment by kaklik** [comment]
Tohle je asi taky vyřešené.
